### Get All Cars
GET {{hostname}}/car-service/api/cars-booking

### Insert Collection of Cars
POST {{hostname}}/car-service/api/cars-booking
Content-Type: application/json

[{
  "brand": "Mercedes-Benz",
  "model": "Class A",
  "costPerDay": 89.50,
  "remainingCars": 10
},
  {
  "brand": "Mercedes-Benz AMG",
  "model": "Class EQE",
  "costPerDay": 236.00,
    "remainingCars": 10
},
  {
  "brand": "Mercedes-Benz AMG",
  "model": "Class EQS",
  "costPerDay": 298.47,
    "remainingCars": 10
}]

### Get a CAR
GET {{hostname}}/car-service/api/cars-booking/733425f4-4ae6-419c-af68-2acc21f249ad

### Book a CAR
POST {{hostname}}/car-service/api/cars-booking/book/52f1fa6f-fff6-4ac9-8893-4b4126d3947f
Content-Type: application/json

{
  "reservationID": "c2770381-45a8-4be5-82f5-fba7307de6c9"
}

### Get All RESERVATIONS
GET {{hostname}}/car-service/api/cars-booking/book
